version: "3.3"
services:
    caddy:
        container_name: caddy-server
        image: caddy:2.0.0-alpine
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes: 
            - ./static:/usr/share/caddy
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./caddy_data:/data
    watchtower:
        container_name: watchtower
        image: v2tec/watchtower
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /home/ubuntu/.docker/config.json:/config.json
        command: watchtower crime-api redb-api --interval 120
    crime-api:
        container_name: crime-api
        image: docker.pkg.github.com/stlrda/crime-api/crime-api:latest
        restart: always
        depends_on:
            - caddy
        ports: 
            - 3000:3000
        environment:
            - DB_HOST=localhost
            - DB_USER=postgres
            - DB_PASS=postgres
            - DB_PORT=5432
            - DB_NAME=crime
    redb-api:
        container_name: redb-api
        image: docker.pkg.github.com/stlrda/redb-api/redb-api:latest
        restart: always
        depends_on:
            - caddy
        ports: 
            - 3001:3001
        environment:
            - DB_HOST=localhost
            - DB_USER=postgres
            - DB_PASS=postgres
            - DB_PORT=5432
            - DB_NAME=redb