version: "3.3"
services:
    caddy:
        container_name: caddy-server
        image: caddy:2.0.0-alpine
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes: 
            - ./index.html:/usr/share/caddy/index.html
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
    crime-api:
        container_name: crime-api
        image: docker.pkg.github.com/stlrda/crime-api/api:latest
        restart: always
        depends_on:
            - caddy
        ports: 
            - 3000:3000
        environment:
            - DB_HOST=localhost
            - DB_USER=postgres
            - DB_PASS=postgres
            - DB_PORT=5432
            - DB_NAME=crime